# Generated by Django 5.1.5 on 2025-01-31 22:26

import despesas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('data_compra', models.DateField(validators=[despesas.models.validar_data_nao_futura], verbose_name='Data da Compra')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos'), ('pecas', 'Peças'), ('produtos', 'Produtos'), ('servicos', 'Serviços'), ('outros', 'Outros')], default='insumos', max_length=20, verbose_name='Categoria')),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('recondicionado', 'Recondicionado'), ('nao_se_aplica', 'Não se aplica')], default='novo', max_length=20, verbose_name='Condição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
